export const countriesData=[
    "Australia",
    "Botswana",
    "Canada",
    "Ethiopia",
    "Ghana",
    "India",
    "Indonesia",
    "Ireland",
    "Israel",
    "Kenya",
    "Latvia",
    "Malaysia",
    "Namibia",
    "New Zealand",
    "Nigeria",
    "Pakistan",
    "Philippines",
    "Singapore",
    "South Africa",
    "Tanzania",
    "Uganda",
    "United Kingdom",
    "United States",
    "Zimbabwe",
    "Czech Republic",
    "Germany",
    "Austria",
    "Switzerland",
    "Argentina",
    "Chile",
    "Colombia",
    "Cuba",
    "Mexico",
    "Peru",
    "Venezuela",
    "Belgium",
    "France",
    "Morocco",
    "Senegal",
    "Italy",
    "Lithuania",
    "Hungary",
    "Netherlands",
    "Norway",
    "Poland",
    "Brazil",
    "Portugal",
    "Romania",
    "Slovakia",
    "Slovenia",
    "Sweden",
    "Vietnam",
    "Turkey",
    "Greece",
    "Bulgaria",
    "Russia",
    "Ukraine",
    "Serbia",
    "United Arab Emirates",
    "Saudi Arabia",
    "Lebanon",
    "Egypt",
    "Bangladesh",
    "Thailand",
    "China",
    "Taiwan",
    "Hong Kong",
    "Japan",
    "Republic of Korea"
  ]