export const universitiesData=[
    'aultman hospita',
    'nyu hospitals center,',
    'university of lagos',
    'drexel university college of medicine',
    'emory university school of medicine',
    'albert einstein college of medicine',
    'state university of new york upstate medical university',
    'university of pennsylvania',
    'southern medical university',
    'philadelphia college of osteopathic medicine',
    'emory university school of medicinefellowship, interventional cardiolog',
    'dow international medical college',
    'alaska pacific university',
    'government medical college, thiruvananthapuram',
    'mercy fitzgerald hospita',
    'cornell university',
    'thanjavur medical college',
    'university of central florida college of medicine',
    "st. john's medical college",
    'indiana university school of medicine',
    'university of wisconsin–madison',
    'universidad autónoma de guadalajara',
    'duke–nus medical school',
    'university of vermont / college of medicine|university of vermont college of medicin',
    'damascus university',
    'university of cincinnati',
    'west virginia university',
    'boston university school of public health',
    'wayne state university school of medicin',
    'king edward memorial hospital and seth gordhandas sunderdas medical college',
    'mount sinai health system',
    'ponce school of medicin',
    'school of sciences, unam',
    'university of maryland, baltimore county',
    'university of benghazi',
    'khyber medical university',
    'liaquat university of medical & health sciences',
    'university of nebraska system',
    'gandhi medical college, bhopal',
    'pontifical catholic university of puerto rico at mayagüez',
    'tulane university school of public health and tropical medicine',
    'united states',
    'university of miami patti and allan herbert business school',
    'nova southeastern university college of osteopathic medicine',
    'perelman school of medicine at the university of pennsylvania',
    'mysore medical college',
    'state university of new york'
  ]
  